#!/usr/bin/env node

/**
 * To simulate real use cases please set the example path into PATH variable
 * export PATH=".":$PATH
 *
 * Then please execute the following line to enable completion for your shell
 * eval "$(auto-complete --completion)"
 *
 * And then you can try use tab completion after auto-complete command
 */

var program = require('..');

program
  .arguments('<a> <b>')
  .option('--verbose', 'verbose')
  .option('-n, --name <name>', 'specify name')
  .option('--description <desc>', 'specify description')
  .complete({
    options: {
      '--name': function() { return ['kate', 'jim']; },
      '--description': ['desc1', 'desc2']
    },
    args: {
      a: function() { return ['a-1', 'a-2']; },
      b: ['b-1', 'b-2']
    }
  })
  .parse(process.argv);
