#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

var list = ['tobi', 'loki', 'jane', 'manny', 'luna'];

console.log('Choose the coolest pet:');
program.choose(list, function(i){
  console.log('you chose %d "%s"', i, list[i]);
  console.log();
  console.log('Choose the coolest pet, defaulting to loki:');
  program.choose(list, 2, function(i){
    console.log('you chose %d "%s"', i, list[i]);
    process.stdin.destroy();
  });
});