#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
  .parse(process.argv);

program.confirm('continue? ', function(ok){
  console.log(' got %j', ok);
  process.stdin.destroy();
});