#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
  .help('-c, --HELP', 'custom help message')
  .option('-s, --sessions', 'add session support')
  .option('-t, --template <engine>', 'specify template engine (jade|ejs) [jade]', 'jade')
  .parse(process.argv);
