#!/usr/bin/env node

// const program = require('commander'); // (normal include)
const program = require('../'); // include commander in git clone of commander repo

program
  .version('0.0.1', '-v, --VERSION', 'new version message')
  .option('-s, --sessions', 'add session support')
  .option('-t, --template <engine>', 'specify template engine (jade|ejs) [jade]', 'jade')
  .parse(process.argv);
