#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
  .version('0.0.1')
  .option('-f, --foo', 'enable some foo')
  .option('-b, --bar', 'enable some bar')
  .option('-B, --baz', 'enable some baz')
  .parse(process.argv);

/* User didn't provide any arguments */
if(program.rawArgs.length<3){ 
  program.help(); 
} else { 
  console.log("User provided some arguments");
}

