#!/usr/bin/env node

// const program = require('commander'); // (normal include)
const program = require('../'); // include commander in git clone of commander repo
const { commanderGlobalEmitter } = require('../')

commanderGlobalEmitter
  .on('help:header', () => {
    console.log('Global Header\n');
  })
  .on('help:body', (instace) => {
    console.log('++++++global++++++');
    console.log(instace.helpInformation().replace(/\n$/, '\n++++++global++++++\n'));
  })
  .on('help:footer', () => {
    console.log(`The End.`);
  })


program
  .version('0.0.1')
  .option('-b, --bar', 'enable some bar')

program
  .on('help:header', () => {
    console.log('Custom Header\n');
  })
  .on('help:body', (instace) => {
    console.log('------local------');
    console.log(instace.helpInformation().replace(/\n$/, '\n------local------\n'));
  })
  .on('help:footer', () => {
    console.log(`Commander - ${new Date().getFullYear()}`);
  })
  .command('foo')
  .action(() => {})

program  
  .parse(process.argv);

/**
 * examples/help-global-listeners -h
 * 
 * Should display both global and "local" emiter messages
 */

/**
 * examples/help-global-listeners foo -h
 * 
 * Should display only global emiter messages
 */