#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program.ask('Username: ', function(name){
  console.log('hi %s', name);

  program.ask('Description:', function(desc){
    console.log('description was "%s"', desc.trim());

    program.ask('Age: ', Number, function(age){
      console.log('age: %j', age);

      program.ask('Birthdate: ', Date, function(date){
        console.log('date: %s', date);
        process.stdin.destroy();
      });
    });
  });
});