#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program.prompt('Username: ', function(name){
  console.log('hi %s\n', name);

  program.prompt('Description:', function(desc){
    console.log('description was "%s"', desc.trim());

    program.prompt('Age: ', Number, function(age){
      console.log('age: %j\n', age);

      program.prompt('Birthdate: ', Date, function(date){
        console.log('date: %s\n', date);
        process.stdin.destroy();
      });
    });
  });
});