#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program.password('Password: ', function(pass){
  console.log('got %j', pass);
  program.password('Password: ', '*', function(pass){
    console.log('got %j', pass);
    program.password('Password: ', '-', function(pass){
      console.log('got %j', pass);
      process.stdin.destroy();
    });
  });
});
