#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program.password('Password: ', function(pass){
  console.log('got "%s"', pass);
  program.prompt('Username: ', function(name){
    console.log('got "%s"', name.trim());
    process.stdin.destroy();
  });
});