#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
  .version('0.0.1')
  .description('Pizza configurator')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineappe')
  .option('-b, --bbq', 'Add bbq sauce')
  .option('-c, --cheese <type>', 'Add the specified type of cheese [cheddar]')
  .option('-C, --no-cheese', 'You do not want any cheese')
  .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineappe) console.log('  - pineappe');
if (program.bbq) console.log('  - bbq');

var cheese = true === program.cheese
  ? 'cheddar'
  : program.cheese || 'no';

console.log('  - %s cheese', cheese);
