#!/usr/bin/env node

var program = require('../../');

program
  .version('0.0.1')
  .command('install [name]', 'install one or more packages').alias('i')
  .command('search [query]', 'search with optional query').alias('s')
  .command('cache', 'actions dealing with the cache').alias('c')
  .command('echo', 'echo arguments')
  .command('list', 'list packages installed').alias('lst')
  .command('listen', 'listen for supported signal events').alias('l')
  .command('publish', 'publish or update package').alias('p')
  .command('default', 'default command', { hidden: true, isDefault: true })
  .command('specifyInstall', 'specify install subcommand', { executableFile: 'pm-install' })
  .command('specifyPublish', 'specify publish subcommand', { executableFile: 'pm-publish' })
  .command('silent', 'silently succeed')
  .parse(process.argv);
