#!/usr/bin/env node

process.on('SIGUSR1', function() {
  process.stdout.write('SIGUSR1');
  process.exit();
});

process.on('SIGUSR2', function() {
  process.stdout.write('SIGUSR2');
  process.exit();
});

process.on('SIGTERM', function() {
  process.stdout.write('SIGTERM');
  process.exit();
});

process.on('SIGINT', function() {
  process.stdout.write('SIGINT');
  process.exit();
});

process.on('SIGHUP', function() {
  process.stdout.write('SIGHUP');
  process.exit();
});

process.stdout.write('Listening for signal...');
setInterval(function() {}, 1000); // Stay running
