#!/usr/bin/env node

var program = require('../../');

program
  .version('0.0.1')
  .command('install [name]', 'install one or more packages')
  .command('search [query]', 'search with optional query')
  .command('list', 'list packages installed')
  .command('publish', 'publish or update package')
  .command('default', 'default command', {noHelp: true, isDefault: true})
  .parse(process.argv);
