#!/usr/bin/env node

var program = require('../../');

program
  .version('0.0.1')
  .command('install [name]', 'install one or more packages').alias('i')
  .command('search [query]', 'search with optional query').alias('s')
  .command('cache', 'actions dealing with the cache').alias('c')
  .command('list', 'list packages installed')
  .command('publish', 'publish or update package').alias('p')
  .command('default', 'default command', {noHelp: true, isDefault: true})
  .parse(process.argv);
