name: build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x, 26.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    # Use separate run commands so command status handled correctly on Windows
    - name: npm install
      run: npm ci
    - name: npm test
      run: npm test
    - name: npm run check
      run: npm run check
